# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[9, 5, 1, 8, 4, 4, 1, 2, 9, 0, 6, 8],
       [9, 4, 9, 1, 7, 0, 1, 5, 2, 0, 4, 0],
       [7, 4, 8, 5, 2, 2, 5, 3, 4, 9, 2, 9],
       [0, 5, 9, 9, 6, 3, 8, 2, 9, 3, 3, 2],
       [2, 3, 4, 1, 3, 6, 2, 8, 2, 4, 6, 0],
       [3, 5, 1, 2, 8, 6, 6, 1, 5, 4, 7, 0],
       [5, 1, 1, 5, 7, 3, 6, 5, 2, 7, 6, 7],
       [9, 9, 6, 1, 0, 7, 7, 0, 0, 1, 8, 1],
       [7, 1, 0, 0, 7, 6, 8, 8, 0, 5, 1, 8],
       [2, 4, 3, 7, 1, 3, 2, 2, 7, 2, 4, 7],
       [9, 9, 0, 3, 8, 1, 6, 9, 4, 3, 4, 8],
       [3, 8, 9, 9, 5, 7, 2, 4, 5, 7, 4, 1]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[9, 5, 1, 8, 4, 4, 1, 2, 9, 0, 6, 8],
       [9, 4, 9, 1, 7, 0, 1, 5, 2, 0, 4, 0],
       [7, 4, 8, 5, 2, 2, 5, 3, 4, 9, 2, 9],
       [0, 5, 9, 9, 6, 3, 8, 2, 9, 3, 3, 2],
       [2, 3, 4, 1, 3, 6, 2, 8, 2, 4, 6, 0],
       [3, 5, 1, 2, 8, 6, 6, 1, 5, 4, 7, 0],
       [5, 1, 1, 5, 7, 3, 6, 5, 2, 7, 6, 7],
       [9, 9, 6, 1, 0, 7, 7, 0, 0, 1, 8, 1],
       [7, 1, 0, 0, 7, 6, 8, 8, 0, 5, 1, 8],
       [2, 4, 3, 7, 1, 3, 2, 2, 7, 2, 4, 7],
       [9, 9, 0, 3, 8, 1, 6, 9, 4, 3, 4, 8],
       [3, 8, 9, 9, 5, 7, 2, 4, 5, 7, 4, 1]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -11,  22, -25,  21, -14,  -7,  12, -10, -15,   8,   0],
       [  0,  -8,   5,   0, -12,  -2,   6,  -4,  -7,  27, -17,   0],
       [  0,   4,  10,  15,   7, -10,  20, -20,  25, -13,  -1,   0],
       [  0,  -4,   2, -14,  -9,  10, -20,  25, -18,   1,  10,   0],
       [  0,  12,  -8,  -7,  14,   1,   9, -20,  11,  -7,  12,   0],
       [  0, -16,  -9,   9,  12, -14,   3,  11,  -9,  15,  -5,   0],
       [  0,  19,  13,  -7, -22,  12,   7, -20,  -3, -16,  23,   0],
       [  0, -16, -10, -15,  21,  -1,   9,  22, -20,  16, -21,   0],
       [  0,   1,   1,  21, -21,   2, -11, -18,  20, -11,   2,   0],
       [  0,  15, -24, -12,  22, -20,  10,  20,  -8,  -5,  -3,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [17]:
img = cv2.imread('img.png', 0)

In [18]:
h,w=img.shape

In [19]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [20]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [21]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()